<?php
use Exports\Module;

$canExport = Module::exportsDirectoryPathIsValid($this->setting('exports_directory_path'));

$this->headLink()->appendStylesheet($this->assetUrl('css/export-browse.css', 'Exports'));

$this->htmlElement('body')->appendAttribute('class', 'exports browse');
?>

<?php echo $this->pageTitle($this->translate('Exports'), 1, $this->translate('Exports')); ?>

<div id="page-actions">
    <?php if ($canExport): ?>
    <?php echo $this->hyperlink($this->translate('Create an export'), $this->url(null, ['action' => 'set-exporter', 'id' => null,], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Label'),
        'value' => 'label',
    ],
    [
        'label' => $this->translate('Exporter'),
        'value' => 'exporter_name',
    ],
]); ?>
</div>

<?php if ($exports): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Exporter'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($exports as $export): ?>
    <?php
    $job = $export->job();
    $owner = $export->owner();
    $reExportUrl = $this->url(
        null,
        ['action' => 'export', 'id' => $export->id()],
        ['query' => ['exporter_name' => $export->exporterName()]],
        true
    );
    ?>
        <tr>
            <td>
                <?php echo $export->label(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $export->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                    <li><?php echo $this->hyperlink('', $reExportUrl, [
                        'class' => 'far fa-copy',
                        'title' => $this->translate('Re-export'),
                    ]); ?></li>
                    <?php if ($export->downloadAvailable()): ?>
                    <li><?php echo $this->hyperlink('', $export->downloadUrl(), [
                        'class' => 'o-icon-download',
                        'title' => $this->translate('Download'),
                    ]); ?></li>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $export->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $this->translate('Delete'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $export->exporterLabel() ?></td>
            <td><?php echo $job ? $job->link($job->statusLabel()) : $this->translate('Unknown'); ?></td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($export->created()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo sprintf(
        $this->translate('No exports found. %s'),
        $canExport ? $this->hyperlink($this->translate('Create a new export.'), $this->url(null, ['action' => 'set-exporter'], true)) : ''
    ); ?></p>
</div>
<?php endif; ?>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>
