<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/export-form.css', 'Exports'));
$this->headScript()->appendFile($this->assetUrl('js/export-form.js', 'Exports'));
$exporter->prepareForm($this);
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('Create an export'), 1, $this->translate('Exports')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'browse', 'id' => null], true), ['class' => 'button']); ?>
    <button type="submit"><?php echo $this->translate('Begin export'); ?></button>
</div>

<?php echo $this->formCollection($form); ?>

<?php echo $this->form()->closeTag(); ?>
