
<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/export-form.css', 'Exports'));
echo $this->pageTitle($this->translate('Create export'), 1, $this->translate('Exports'));
?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'browse'], true), ['class' => 'button']); ?>
    <button><?php echo $this->translate('Next'); ?></button>
</div>

<h3><?php echo $this->translate('What would you like to export?'); ?></h3>

<?php foreach ($form->getExporters() as $exporterName => $exporter): ?>
<div class="exporter">
    <label>
        <input type="radio" name="<?php echo $this->escapeHtml('exporter_name'); ?>" value="<?php echo $this->escapeHtml($exporterName); ?>" required>
        <?php echo $this->escapeHtml($this->translate($exporter->getLabel())); ?>
    </label>
    <?php if ($exporter->getDescription()): ?>
    <div class="exporter-description"><?php echo $this->translate($exporter->getDescription()); ?></div>
    <?php endif; ?>
</div>
<?php endforeach; ?>

<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>
